nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmScopes:
  "react-admin":
    npmAlwaysAuth: true
    npmAuthToken: 6511b722-6f58-4932-8541-7c38d18da888 # change with your token
    npmRegistryServer: "https://registry.marmelab.com"